services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_oficina
    environment:
      POSTGRES_DB: oficina
      POSTGRES_USER: oficina
      POSTGRES_PASSWORD: oficina
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - oficina_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oficina"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tc_oficina_app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/oficina
      SPRING_DATASOURCE_USERNAME: oficina
      SPRING_DATASOURCE_PASSWORD: oficina
    networks:
      - oficina_network

volumes:
  postgres_data:

networks:
  oficina_network:
