spring:
  application:
    name: tc-oficina

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/oficina}
    username: ${SPRING_DATASOURCE_USERNAME:oficina}
    password: ${SPRING_DATASOURCE_PASSWORD:oficina}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24h em ms

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
  api-docs:
    path: /v1/api-docs

management:
  otlp:
    metrics:
      export:
        enabled: false
  server:
    port: ${MANAGEMENT_SERVER_PORT:8081}
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0}

  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        oficina.ordens.status.duracao: true
