management:
  opentelemetry:
    resource-attributes:
      service.name: ${OTEL_SERVICE_NAME:tc-oficina}
      deployment.environment: ${DEPLOYMENT_ENVIRONMENT:production}
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:https://otlp.nr-data.net/v1/traces}
          headers:
            api-key: ${NEW_RELIC_LICENSE_KEY}
          transport: http
