apiVersion: v1
kind: Secret

metadata:
  name: spring-api-secret
  namespace: of-fiap

type: Opaque

# ===== Em produção utilizar External Secrets, Vault ou Secrets Manager. ====

stringData:
  SPRING_DATASOURCE_USERNAME: oficina

  SPRING_DATASOURCE_PASSWORD: oficina

  JWT_SECRET: T3Nno4Ipybddv14B1yGQmyl2KudK2dRw91708DQuo2E=
