name: Oficina FIAP CI-CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/spring-api:${{ github.sha }}

jobs:

  build-test-package:

    runs-on:
      - self-hosted
      - windows
      - of-fiap-1

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Build + Tests
        run: .\mvnw.cmd clean verify

      - name: Publicar artefato
        uses: actions/upload-artifact@v4
        with:
          name: spring-jar
          path: target/*.jar

  docker-build-push:

    needs: build-test-package

    runs-on:
      - self-hosted
      - windows
      - of-fiap-1

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .

      - name: Push Docker Image
        run: |
          docker push ${{ env.IMAGE_NAME }}

  deploy-kubernetes:

    needs: docker-build-push

    runs-on:
      - self-hosted
      - windows
      - of-fiap-1

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Verificar cluster
        run: |
          kubectl get nodes

      - name: Criar namespace
        run: |
          kubectl apply -f k8s/namespace.yaml

      - name: Aplicar ConfigMap
        shell: powershell
        run: |
          kubectl create configmap spring-api-config `
            --from-literal=SPRING_DATASOURCE_URL="jdbc:postgresql://${{ vars.DB_HOST }}:5432/oficina" `
            --namespace=of-fiap `
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Aplicar Secret
        shell: powershell
        run: |
          kubectl create secret generic spring-api-secret `
            --from-literal=SPRING_DATASOURCE_USERNAME="${{ secrets.DB_USERNAME }}" `
            --from-literal=SPRING_DATASOURCE_PASSWORD="${{ secrets.DB_PASSWORD }}" `
            --from-literal=JWT_SECRET="${{ secrets.JWT_SECRET }}" `
            --namespace=of-fiap `
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Atualizar imagem da aplicação
        shell: powershell
        run: |
          (Get-Content k8s/app-deployment.yaml) `
          -replace 'IMAGE_NAME','${{ env.IMAGE_NAME }}' |
          Set-Content k8s/app-deployment-generated.yaml

      - name: Deploy aplicação
        run: |
          kubectl apply -f k8s/app-deployment-generated.yaml

      - name: Expor aplicação
        run: |
          kubectl apply -f k8s/app-service.yaml

      - name: Criar Ingress
        run: |
          kubectl apply -f k8s/app-ingress.yaml

      - name: Aguardar rollout
        run: |
          kubectl rollout status deployment/spring-api -n of-fiap

      - name: Exibir recursos
        run: |
          kubectl get all
